name: OSDev CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test KenOS
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      GITHUB_DIR: ${{ github.workspace }}

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        echo $DOCKER_PASS | docker login --username $DOCKER_USER --password-stdin
        docker pull hoshiyamazaki/kenos-build:alphadocker
        docker run -w $GITHUB_DIR -v $GITHUB_DIR:$GITHUB_DIR hoshiyamazaki/kenos-build:alphadocker /bin/bash -c "export PATH=/opt/local/bin:$PATH; echo $PATH; ls /opt/local/bin; make"
